var strVar="";
strVar += "<style type=\"text\/css\">";
strVar += "#gb2{";
strVar += "position:fixed;";
strVar += "top:150px;";
strVar += "z-index:+1000;";
strVar += "}";
strVar += "* html #gb2{position:relative;}";
strVar += "";
strVar += ".gb2tab{";
strVar += "height:180px;";
strVar += "width:50px;";
strVar += "float:left;";
strVar += "cursor:pointer;";
strVar += "background:url('..\/2.bp.blogspot.com\/-n-ZnLgqWmMU\/VFLlz6azOuI\/AAAAAAAAA0Y\/3rwO2Ubt3Dw\/s1600\/fecharxat2.png') no-repeat;";
strVar += "}";
strVar += ".gb2content{";
strVar += "float:left;";
strVar += "border:2px solid #999999;";
strVar += "background:#ffffff;";
strVar += "padding:0px;";
strVar += "}";
strVar += "";
strVar += "<\/style>";
strVar += "";
strVar += "";
strVar += "<script type=\"text\/javascript\">";
strVar += "function showHideGB2(){";
strVar += "var gb2 = document.getElementById(\"gb2\");";
strVar += "var w = gb2.offsetWidth;";
strVar += "gb2.opened ? moveGB2(0, 50-w) : moveGB2(21-w, 0);";
strVar += "gb2.opened = !gb2.opened;";
strVar += "}";
strVar += "function moveGB2(x0, xf){";
strVar += "var gb2 = document.getElementById(\"gb2\");";
strVar += "var dx = Math.abs(x0-xf) > 10 ? 5 : 1;";
strVar += "var dir = xf>x0 ? 1 : -1;";
strVar += "var x = x0 + dx * dir;";
strVar += "gb2.style.right = x.toString() + \"px\";";
strVar += "if(x0!=xf){setTimeout(\"moveGB2(\"+x+\", \"+xf+\")\", 10);}";
strVar += "}";
strVar += "<\/script>";
strVar += "";
strVar += "";
strVar += "";
strVar += "";
strVar += " ";
strVar += "";
strVar += "<div id=\"gb2\" style=\"right: -500px;\">";
strVar += "";
strVar += "<div onclick=\"showHideGB2()\" class=\"gb2tab\"> <\/div>";
strVar += "";
strVar += "<div class=\"gb2content\">";
strVar += "";
strVar += "";
strVar += "<div style=\"text-align: center; line-height: 0\" id=\"cboxdiv\">";
strVar += "<div style=\"margin-right:0px\">";
strVar += "<p>";
strVar += "<object classid=\"clsid:d27cdb6e-ae6d-11cf-96b8-444553540000\" codebase=\"\/\/fpdownload.macromedia.com\/pub\/shockwave\/cabs\/flash\/swflash.cab#version=8,0,0,0\" width=\"400\" height=\"400\" id=\"chat\" align=\"middle\">";
strVar += "<param name=\"allowScriptAccess\" value=\"sameDomain\" \/>";
strVar += "<param name=\"movie\" value=\"\/\/www.xatech.com\/web_gear\/chat\/chat.swf\" \/>";
strVar += "<param name=\"quality\" value=\"high\" \/><param name=\"bgcolor\" value=\"#000000\" \/>";
strVar += "<param name=\"FlashVars\" value=\"id=64735703&xc=3360&cn=444659904&gb=7tG4d&gn=TradeStore\" \/><param name=\"wmode\" value=\"transparent\" \/>";
strVar += "<embed src=\"\/\/www.xatech.com\/web_gear\/chat\/chat.swf\" quality=\"high\" wmode=\"transparent\" bgcolor=\"#000000\" width=\"400\" height=\"400\" name=\"chat\" FlashVars=\"id=64735703&xc=3360&cn=444659904&gb=7tG4d&gn=TradeStore\" align=\"middle\" allowScriptAccess=\"sameDomain\" type=\"application\/x-shockwave-flash\" pluginspage=\"\/\/xat.com\/update_flash.shtml\" \/>";
strVar += "<\/object>";
strVar += "";
strVar += "<\/p>";
strVar += "<p>";
strVar += "<object classid=\"clsid:d27cdb6e-ae6d-11cf-96b8-444553540000\" codebase=\"\/\/fpdownload.macromedia.com\/pub\/shockwave\/cabs\/flash\/swflash.cab#version=8,0,0,0\" width=\"400\" height=\"400\" id=\"chat\" align=\"middle\">";
strVar += "<param name=\"allowScriptAccess\" value=\"sameDomain\" \/>";
strVar += "<param name=\"movie\" value=\"\/\/www.xatech.com\/web_gear\/chat\/chat.swf\" \/>";
strVar += "<param name=\"quality\" value=\"high\" \/><param name=\"bgcolor\" value=\"#000000\" \/>";
strVar += "<param name=\"FlashVars\" value=\"id=59653268&xc=3360&cn=1238379745&gb=7VcYp2&gn=TradeBrasil\" \/><param name=\"wmode\" value=\"transparent\" \/>";
strVar += "<embed src=\"\/\/www.xatech.com\/web_gear\/chat\/chat.swf\" quality=\"high\" wmode=\"transparent\" bgcolor=\"#000000\" width=\"400\" height=\"400\" name=\"chat\" flashvars=\"id=59653268&xc=3360&cn=1238379745&gb=7VcYp2&gn=TradeBrasil\" align=\"middle\" allowscriptaccess=\"sameDomain\" type=\"application\/x-shockwave-flash\" pluginspage=\"\/\/xat.com\/update_flash.shtml\" \/>";
strVar += "<\/embed><\/object>";
strVar += "<\/p>";
strVar += "<p>";
strVar += "<object classid=\"clsid:d27cdb6e-ae6d-11cf-96b8-444553540000\" codebase=\"\/\/fpdownload.macromedia.com\/pub\/shockwave\/cabs\/flash\/swflash.cab#version=8,0,0,0\" width=\"400\" height=\"400\" id=\"chat\" align=\"middle\">";
strVar += "<param name=\"allowScriptAccess\" value=\"sameDomain\" \/>";
strVar += "<param name=\"movie\" value=\"\/\/www.xatech.com\/web_gear\/chat\/chat.swf\" \/>";
strVar += "<param name=\"quality\" value=\"high\" \/><param name=\"bgcolor\" value=\"#000000\" \/>";
strVar += "<param name=\"FlashVars\" value=\"id=53758255&xc=2336&cn=1501910450&gb=7tG4d&gn=Parceria\" \/>";
strVar += "<embed src=\"\/\/www.xatech.com\/web_gear\/chat\/chat.swf\" quality=\"high\" bgcolor=\"#000000\" width=\"400\" height=\"400\" name=\"chat\" FlashVars=\"id=53758255&xc=2336&cn=1501910450&gb=7tG4d&gn=Parceria\" align=\"middle\" allowScriptAccess=\"sameDomain\" type=\"application\/x-shockwave-flash\" pluginspage=\"\/\/xat.com\/update_flash.shtml\" \/>";
strVar += "<\/object>";
strVar += "<\/p>";
strVar += "<p>";
strVar += "<object classid=\"clsid:d27cdb6e-ae6d-11cf-96b8-444553540000\" codebase=\"\/\/fpdownload.macromedia.com\/pub\/shockwave\/cabs\/flash\/swflash.cab#version=8,0,0,0\" width=\"400\" height=\"400\" id=\"chat\" align=\"middle\">";
strVar += "<param name=\"allowScriptAccess\" value=\"sameDomain\" \/>";
strVar += "<param name=\"movie\" value=\"\/\/www.xatech.com\/web_gear\/chat\/chat.swf\" \/>";
strVar += "<param name=\"quality\" value=\"high\" \/><param name=\"bgcolor\" value=\"#000000\" \/>";
strVar += "<param name=\"FlashVars\" value=\"id=55027968&xc=2336&cn=801096926&gb=7tG4d&gn=Divulgacao\" \/>";
strVar += "<embed src=\"\/\/www.xatech.com\/web_gear\/chat\/chat.swf\" quality=\"high\" bgcolor=\"#000000\" width=\"400\" height=\"400\" name=\"chat\" FlashVars=\"id=55027968&xc=2336&cn=801096926&gb=7tG4d&gn=Divulgacao\" align=\"middle\" allowScriptAccess=\"sameDomain\" type=\"application\/x-shockwave-flash\" pluginspage=\"\/\/xat.com\/update_flash.shtml\" \/>";
strVar += "<\/object>";
strVar += "<\/p>";
strVar += "<p>";
strVar += "<div id=\"muteYouTubeVideoPlayer\">";
strVar += "<\/div>";
strVar += "<script async src=\"https:\/\/www.youtube.com\/iframe_api\"><\/script>";
strVar += "<script>";
strVar += " function onYouTubeIframeAPIReady() {";
strVar += "  var player;";
strVar += "  player = new YT.Player('muteYouTubeVideoPlayer', {";
strVar += "    videoId: 'Y3nxTuzui2M', \/\/ YouTube Video ID";
strVar += "    width: 400,               \/\/ Player width (in px)";
strVar += "    height: 280,              \/\/ Player height (in px)";
strVar += "    playerVars: {";
strVar += "      autoplay: 1,        \/\/ Auto-play the video on load";
strVar += "      controls: 1,        \/\/ Show pause\/play buttons in player";
strVar += "      showinfo: 0,        \/\/ Hide the video title";
strVar += "      modestbranding: 1,  \/\/ Hide the Youtube Logo";
strVar += "      loop: 1,            \/\/ Run the video in a loop";
strVar += "      fs: 0,              \/\/ Hide the full screen button";
strVar += "      cc_load_policy: 0, \/\/ Hide closed captions";
strVar += "      iv_load_policy: 3,  \/\/ Hide the Video Annotations";
strVar += "      autohide: 0         \/\/ Hide video controls when playing";
strVar += "    },";
strVar += "    events: {";
strVar += "      onReady: function(e) {";
strVar += "        e.target.mute();";
strVar += "      }";
strVar += "    }";
strVar += "  });";
strVar += " }";
strVar += "<\/script>";
strVar += "<\/p>";
strVar += "<\/div><\/div><\/div><\/div>";
